export const ROLES = Object.freeze({
  ADMIN: 'admin',
  STUDENT: 'student',
});

export const ACCOUNT_STATUS = Object.freeze({
  PENDING_SETUP: 'PENDING_SETUP',
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
});

export const REQUEST_TYPE = Object.freeze({
  BRANCH_CHANGE: 'BRANCH_CHANGE',
  DATE_SHEET_CHANGE: 'DATE_SHEET_CHANGE',
});

export const REQUEST_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

export const EMAIL_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  DISABLED: 'DISABLED',
});

export const AUDIT_ACTION = Object.freeze({
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  STUDENT_CREATED: 'STUDENT_CREATED',
  STUDENT_UPDATED: 'STUDENT_UPDATED',
  STUDENT_DEACTIVATED: 'STUDENT_DEACTIVATED',
  BRANCH_CREATED: 'BRANCH_CREATED',
  BRANCH_UPDATED: 'BRANCH_UPDATED',
  BRANCH_DEACTIVATED: 'BRANCH_DEACTIVATED',
  COURSE_CREATED: 'COURSE_CREATED',
  COURSE_UPDATED: 'COURSE_UPDATED',
  COURSE_DEACTIVATED: 'COURSE_DEACTIVATED',
  SLOT_CREATED: 'SLOT_CREATED',
  SLOT_UPDATED: 'SLOT_UPDATED',
  SLOT_DEACTIVATED: 'SLOT_DEACTIVATED',
  ASSIGNMENT_UPDATED: 'ASSIGNMENT_UPDATED',
  REQUEST_REVIEWED: 'REQUEST_REVIEWED',
  SETUP_EMAIL_RESENT: 'SETUP_EMAIL_RESENT',
});

export const BRANCH_SEAT_TOTAL = 60;

export const ASSIGNMENT_MIN = 4;
export const ASSIGNMENT_MAX = 6;

export default {
  ROLES,
  ACCOUNT_STATUS,
  REQUEST_TYPE,
  REQUEST_STATUS,
  EMAIL_STATUS,
  AUDIT_ACTION,
  ASSIGNMENT_MIN,
  ASSIGNMENT_MAX,
};
